api_platform:
    title: 'LOL'
    description: 'Get lol champ base data'
    version: 'beta'
    show_webby: false
    swagger:
         api_keys:
             JWT:
                name: Authorization
                type: header